import test from 'node:test';import assert from 'node:assert/strict';import {readFile,stat} from 'node:fs/promises';
const d=JSON.parse(await readFile('data/properties.json','utf8'));const ps=d.properties;const find=id=>ps.find(p=>p.sources.some(s=>s.id===id));
test('Every fact has a valid original-source provenance and timestamp',()=>{assert.equal(new Set(ps.map(p=>p.id)).size,ps.length);for(const p of ps){const ids=new Set(p.sources.map(s=>s.id));for(const s of p.sources){assert.match(s.url,/^https:\/\//);assert.ok(Number.isFinite(Date.parse(s.checkedAt)));assert.ok(['appears_available','unconfirmed'].includes(s.availability));}for(const vs of Object.values(p.facts))for(const v of vs){assert.ok(v.sourceIds.length);assert.ok(v.sourceIds.every(s=>ids.has(s)));}}});
test('Withdrawn originals and industrial land do not survive as residential cards',()=>{for(const id of ['altamira-PR33491','altamira-PR37557','altamira-PR37706','buysellcyprus-1312464'])assert.equal(find(id),undefined);assert.ok(ps.every(p=>p.type==='field'||p.type==='plot'));assert.ok(!ps.some(p=>p.sources.some(s=>[846,4534,2174,1924].includes(s.advertisedArea))));});
test('Photo-confirmed duplicates merge, equal-area distinct plots remain separate',()=>{assert.equal(find('bazaraki-6584620').id,find('forsale-348962').id);assert.equal(find('remu-16963').id,find('forsale-237882').id);assert.notEqual(find('bazaraki-6540212').id,find('forsale-245121').id);assert.notEqual(find('bazaraki-6633409').id,find('indexcy-4057990').id);});
test('Price and area conflicts are retained per source',()=>{const p=find('altamira-PR42579');assert.deepEqual(p.facts.price.map(x=>x.value).sort((a,b)=>a-b),[55000,57500]);assert.ok(p.conflictFields.includes('price'));assert.ok(find('forsale-245121').conflictFields.includes('area'));});
test('No-access and ambiguous shares cannot become ordinary building plots',()=>{for(const id of ['forsale-411106','forsale-411105','remu-41256']){const p=find(id);assert.equal(p.landlocked,true);assert.equal(p.registeredRoad,false);assert.equal(p.normalPlot,false);}const p=find('bazaraki-6052151');assert.equal(p.isShare,true);assert.ok(p.sources.some(s=>s.areaBasis==='ambiguous_share_or_whole'));assert.equal(find('altamira-PR36973').facts.area[0].value,1975);});
test('Summary counts reconcile with the dataset',()=>{assert.equal(d.meta.uniqueProperties,ps.length);assert.equal(d.meta.allPlots+d.meta.residentialFields,ps.length);assert.equal(d.meta.shares,ps.filter(p=>p.isShare).length);assert.equal(d.meta.includedSourceListings,ps.reduce((n,p)=>n+p.sources.length,0));});
test('Every published local photo exists and retains its source URL',async()=>{for(const p of ps)for(const im of p.images){assert.match(im.url,/^https:\/\//);assert.ok(im.localPath?.startsWith('images/'));assert.ok((await stat(im.localPath)).size>0);}});
